//
// This code was auto-generated by the Mayope API builder.
//

/// A Mayope API Service.
public protocol MayopeService {
    /// The login action.
    func login(request: LoginRequest) -> LoginResponse

    /// The logout action.
    func logout(request: LogoutRequest) -> LogoutResponse

    /// The forest list action.
    func listForests(request: ListForestsRequest) -> ListForestsResponse

    /// The tree list action.
    func listTrees(request: ListTreesRequest) -> ListTreesResponse

    /// The branch list action.
    func listBranches(request: ListBranchesRequest) -> ListBranchesResponse
}
