/*
 * This code was auto-generated by the Mayope API builder.
 */

package org.mayope.api.responses;

import java.util;

/**
 * A successful login response including the authentication token to use in
 * future authenticated requests.
 */
public class LoginResponse implements Response {
    /**
     * An authentication token to use in future requests.
     */
    private UUID token;

    /**
     * Get an authentication token to use in future requests.
     *
     * @return The value
     */
    public UUID getToken() {
        return token;
    }

    /**
     * Set an authentication token to use in future requests.
     *
     * @param token A new value
     */
    public void setToken(UUID token) {
        this.token = token;
    }
}
