/*
 * This code was auto-generated by the Mayope API builder.
 */

package org.mayope.api.responses;

/**
 * A logout confirmation response.
 */
public class LogoutResponse extends SuccessResponse {
}
