/*
 * This code was auto-generated by the Mayope API builder.
 */

package org.mayope.api.responses;

/**
 * A response message (server -> client).
 */
public interface Response implements Message {
}
