//
// This code was auto-generated by the Mayope API builder.
//

/// Details of a branch in a Mayope schema.
public class Branch : Node {
    /// The type of the branch's value.
    var type: BranchType { get set }

    /// Additional size specifiers for the type if needed.
    var sizes: Array<Int> { get set }

    /// The child branch type(s) if not a single-valued type.
    var branches: Array<Branch> { get set }
}
