//
// This code was auto-generated by the Mayope API builder.
//

/// Possible types of a branch.
public enum BranchType : String {
    /// A boolean true/false values.
    case boolean = "Boolean"
    /// An integer value; sizes[0] is the number of bits (8, 16, 32, 64),
    /// sizes[1] is 0 for unsigned, 1 for signed.
    case integer = "Integer"
    /// A floating-point number; sizes[0] is the number of bits (32, 64).
    case float = "Float"
    /// A decimal number; sizes[0] is the maximum number of digits before the
    /// decimal point, sizes[1] is the maximum number of digits after.
    case decimal = "Decimal"
    /// A string of UTF8 charcters; sizes[0] is the maximum length in
    /// characters.
    case string = "String"
    /// A UUID.
    case uuid = "Uuid"
    /// An ordered list of values; branches[0] is the type of the values.
    case list = "List"
    /// An unordered set of values; branches[0] is the type of the values.
    case set = "Set"
    /// A map of values; branches[0] is the type of the keys, branches[1] is
    /// the type of the values.
    case map = "Map"
    /// A tree of sub-values, as specified by branches[].
    case tree = "Tree"
}
