//
// This code was auto-generated by the Mayope API builder.
//

/// Details of a branch in a Mayope schema.
public class Branch : Node {
    /// The type of the branch's value.
    var type: String { get set }

    /// The child branches if the type involves a Tree.
    var branches: Branch { get set }
}
