//
// This code was auto-generated by the Mayope API builder.
//

/// A type of error.
public enum ErrorType : String {
    /// An unknown error.
    case unknown = "Unknown"
    /// The input was invalid.
    case validation = "Validation"
    /// An authentication failure (i.e. invalid credentials, etc).
    case authentication = "Authentication"
    /// An authorization failure (i.e. user does not have access).
    case authorization = "Authorization"
}
