//
// This code was auto-generated by the Mayope API builder.
//

/// Details of a forest.
public class Forest : Node {
    /// The children of this forest; empty if none, null if this is a stub
    /// record.
    var forests: Array<Forest> { get set }

    /// The trees within this forest; empty if none, null if this is a stub
    /// record.
    var trees: Array<Tree> { get set }
}
