//
// This code was auto-generated by the Mayope API builder.
//

import Foundation

/// A node in a Myaope schema.
public class Node {
    /// A universally unique identifier for the node.
    var uuid: UUID { get set }

    /// An ID which must be unique amongst sibling nodes.
    var id: String { get set }

    /// A plain-text name for the node.
    var name: String { get set }

    /// A free-text description of the node.
    var description: String { get set }
}
