//
// This code was auto-generated by the Mayope API builder.
//

/// Details of a tree.
public class Tree : Node {
    /// The branches within this tree; empty if none, null if this is a stub
    /// record.
    var branches: Array<Branch> { get set }
}
