/*
 * This code was auto-generated by the Mayope API builder.
 */

package org.mayope.api;

import org.mayope.api.requests;
import org.mayope.api.responses;

/**
 * A Mayope API Service.
 */
public interface MayopeService {
    /**
     * The login action.
     *
     * @param request A request message
     * @return The response message
     */
    LoginResponse login(LoginRequest request);

    /**
     * The logout action.
     *
     * @param request A request message
     * @return The response message
     */
    LogoutResponse logout(LogoutRequest request);

    /**
     * The forest list action.
     *
     * @param request A request message
     * @return The response message
     */
    ListForestsResponse listForests(ListForestsRequest request);

    /**
     * The tree list action.
     *
     * @param request A request message
     * @return The response message
     */
    ListTreesResponse listTrees(ListTreesRequest request);

    /**
     * The branch list action.
     *
     * @param request A request message
     * @return The response message
     */
    ListBranchesResponse listBranches(ListBranchesRequest request);
}
