/*
 * This code was auto-generated by the Mayope API builder.
 */

package org.mayope.api.types;

/**
 * Possible types of a branch.
 */
public enum BranchType {
    /**
     * A boolean true/false values.
     */
    Boolean,
    /**
     * An integer value; sizes[0] is the number of bits (8, 16, 32, 64),
     * sizes[1] is 0 for unsigned, 1 for signed.
     */
    Integer,
    /**
     * A floating-point number; sizes[0] is the number of bits (32, 64).
     */
    Float,
    /**
     * A decimal number; sizes[0] is the maximum number of digits before the
     * decimal point, sizes[1] is the maximum number of digits after.
     */
    Decimal,
    /**
     * A string of UTF8 charcters; sizes[0] is the maximum length in
     * characters.
     */
    String,
    /**
     * A UUID.
     */
    Uuid,
    /**
     * An ordered list of values; branches[0] is the type of the values.
     */
    List,
    /**
     * An unordered set of values; branches[0] is the type of the values.
     */
    Set,
    /**
     * A map of values; branches[0] is the type of the keys, branches[1] is the
     * type of the values.
     */
    Map,
    /**
     * A tree of sub-values, as specified by branches[].
     */
    Tree;
}
