/*
 * This code was auto-generated by the Mayope API builder.
 */

package org.mayope.api.types;

import java.util;

/**
 * Details of a forest.
 */
public class Forest extends Node {
    /**
     * The children of this forest; empty if none, null if this is a stub
     * record.
     */
    private List<Forest> forests;

    /**
     * The trees within this forest; empty if none, null if this is a stub
     * record.
     */
    private List<Tree> trees;

    /**
     * Get the children of this forest; empty if none, null if this is a stub
     * record.
     *
     * @return The value
     */
    public List getForests() {
        return forests;
    }

    /**
     * Set the children of this forest; empty if none, null if this is a stub
     * record.
     *
     * @param forests A new value
     */
    public void setForests(List forests) {
        this.forests = forests;
    }

    /**
     * Get the trees within this forest; empty if none, null if this is a stub
     * record.
     *
     * @return The value
     */
    public List getTrees() {
        return trees;
    }

    /**
     * Set the trees within this forest; empty if none, null if this is a stub
     * record.
     *
     * @param trees A new value
     */
    public void setTrees(List trees) {
        this.trees = trees;
    }
}
