/*
 * This code was auto-generated by the Mayope API builder.
 */

package org.mayope.api.requests;

/**
 * A request to log out, expiring the given token.
 */
public class LogoutRequest extends AuthenticatedRequest {
}
