// <auto-generated>
// This code was auto-generated by the Mayope API builder.
// </auto-generated>

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

using Newtonsoft.Json;

namespace Mayope.Api.Types
{
    /// <summary>
    /// Details of a branch in a Mayope schema.
    /// </summary>
    public class Branch : Node
    {
        /// <summary>
        /// The type of the branch's value.
        /// </summary>
        [Required]
        [JsonRequired]
        public BranchType Type { get; set; }

        /// <summary>
        /// Additional size specifiers for the type if needed.
        /// </summary>
        public IList<int> Sizes { get; set; }

        /// <summary>
        /// The child branch type(s) if not a single-valued type.
        /// </summary>
        public IList<Branch> Branches { get; set; }
    }
}
