// <auto-generated>
// This code was auto-generated by the Mayope API builder.
// </auto-generated>

namespace Mayope.Api.Types
{
    /// <summary>
    /// An integer value.
    /// </summary>
    public class Integer
    {
    }
}
