//
// This code was auto-generated by the Mayope API builder.
//

import Foundation

/// A request for a list of trees.
public class ListTreesRequest : AuthenticatedRequest {
    /// The UUID of the forest to list the trees in.
    var forest: UUID { get set }
}
