//
// This code was auto-generated by the Mayope API builder.
//

import Foundation

/// A request for a list of branches.
public class ListBranchesRequest : AuthenticatedRequest {
    /// The UUID of the tree to list the branches in.
    var tree: UUID { get set }
}
