//
// This code was auto-generated by the Mayope API builder.
//

import Foundation

/// A request for a list of forests.
public class ListForestsRequest : AuthenticatedRequest {
    /// The UUID of a forest to list the children of, or null for the root
    /// forests.
    var parent: UUID { get set }
}
