//
// This code was auto-generated by the Mayope API builder.
//

/// A login request, including username/password credentials.
public class LoginRequest : Request {
    /// The username to log in with.
    var username: String { get set }

    /// The user's password.
    var password: String { get set }
}
