//
// This code was auto-generated by the Mayope API builder.
//

/// An error response. This may be returned as an alternative response to any
/// action, normally with an error indication in the underlying protocol (e.g.
/// a 4xx or 5xx HTTP status code).
public class ErrorResponse : Response {
    /// A code giving the type of error which occurred.
    var error: ErrorType { get set }

    /// A more detailed, human-readable error message.
    var message: String { get set }

    /// Additional details of the error.
    var details: Dictionary<String,String> { get set }
}
