//
// This code was auto-generated by the Mayope API builder.
//

import Foundation

/// A response containing a list of branches.
public class ListBranchesResponse {
    /// The UUID of the tree.
    var tree: UUID { get set }

    /// The branches in the tree, empty if none.
    var branches: Array<Branch> { get set }
}
