//
// This code was auto-generated by the Mayope API builder.
//

import Foundation

/// A response containing a list of trees.
public class ListTreesResponse {
    /// The UUID of the forest.
    var forest: UUID { get set }

    /// The trees in the forest, empty if none.
    var trees: Array<Tree> { get set }
}
