//
// This code was auto-generated by the Mayope API builder.
//

/// A geneic boolean success/failure response.
public class SuccessResponse : Response {
    /// True if the operation succeeded, false otherwise.
    var success: Bool { get set }
}
